title: Accueil
description: Portfolio de projets EPFL
theme: minima

# Menu
header_pages:
  - cv.fr.md
  - projets.md

# CSS custom
include:
  - assets/css

plugins:
  - jekyll-polyglot

languages: ["fr", "en"]
default_lang: "fr"
