title: Accueil
description: Portfolio
theme: minima

# Menu
header_pages:
  - fr/cv.md
  - fr/projets.md

# CSS custom
include:
  - assets/css

plugins:
  - jekyll-polyglot

languages: ["fr", "en"]
default_lang: "fr"
